import { KnowledgePolicy } from "../models/KnowledgePolicy.js";

export const knowledgeBase = [
  new KnowledgePolicy("KB-01", "Password Reset",
    "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required."),
  new KnowledgePolicy("KB-02", "VPN Access",
    "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."),
  new KnowledgePolicy("KB-03", "Laptop Replacement",
    "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."),
  new KnowledgePolicy("KB-04", "Software Installation",
    "Requests for standard software listed in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days."),
  new KnowledgePolicy("KB-05", "Printer Troubleshooting",
    "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer’s asset tag."),
  new KnowledgePolicy("KB-06", "Email Mailbox Quota",
    "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB."),
  new KnowledgePolicy("KB-07", "Guest Wi-Fi Access",
    "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required."),
  new KnowledgePolicy("KB-08", "Expense Software Access",
    "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists."),
  new KnowledgePolicy("KB-09", "Security Incident Reporting",
    "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees."),
  new KnowledgePolicy("KB-10", "Work-From-Home Equipment",
    "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."),
  new KnowledgePolicy("ASSET", "Asset Management Policy",
    "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval.")
];
